# Generated by Django 5.0.3 on 2024-03-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.URLField(blank=True, max_length=250)),
                ('hostname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('profile', models.URLField(blank=True, max_length=250)),
                ('remotePosts', models.URLField(blank=True, max_length=250)),
                ('remoteInbox', models.URLField(blank=True, max_length=250)),
                ('requesters', models.TextField(blank=True, default='[]')),
                ('followers', models.TextField(blank=True, default='[]')),
            ],
        ),
    ]
