# Generated by Django 5.0.3 on 2024-03-25 19:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projuser',
            name='otherURL',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='messagesuper',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='messagesuper',
            name='origin',
            field=models.CharField(db_column='origin', max_length=50),
        ),
    ]
