# Generated by Django 5.0.2 on 2024-03-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
