# Generated by Django 5.0.2 on 2024-03-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0019_post_content_type_alter_user_bio_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html_content',
            field=models.TextField(blank=True),
        ),
    ]
