# Generated by Django 5.0.2 on 2024-03-09 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0022_messagesuper'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesuper',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='SocialDistribution.post'),
        ),
    ]
