# Generated by Django 5.0.3 on 2024-03-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0024_user_github_username_githubactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recent_processed_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
