# Generated by Django 5.0.2 on 2024-03-11 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0024_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
