# Generated by Django 5.0.2 on 2024-03-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0026_imagepost_delete_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_data',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='ImagePost',
        ),
    ]
