# Generated by Django 5.0.2 on 2024-03-12 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0024_user_github_username_githubactivity'),
        ('SocialDistribution', '0028_alter_post_content'),
    ]

    operations = [
    ]
