# Generated by Django 5.0.2 on 2024-03-13 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0025_user_recent_processed_activity'),
        ('SocialDistribution', '0029_merge_20240312_1626'),
    ]

    operations = [
    ]
