# Generated by Django 5.0.2 on 2024-03-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0030_merge_20240313_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8),
        ),
    ]
