# Generated by Django 5.0.2 on 2024-03-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0030_merge_20240313_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
