# Generated by Django 5.0.3 on 2024-03-16 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0031_alter_post_image_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('host', models.URLField()),
                ('userAPI', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SignUpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_signup_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='following',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='server_node',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SocialDistribution.servernode'),
        ),
    ]
