# Generated by Django 5.0.3 on 2024-03-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0032_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_signup_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
