# Generated by Django 5.0.2 on 2024-03-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0031_following_status'),
        ('SocialDistribution', '0032_servernode_signupsettings_following_status_and_more'),
        ('SocialDistribution', '0034_servernode_user_server_node'),
    ]

    operations = [
    ]
