# Generated by Django 5.0.3 on 2024-03-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDistribution', '0035_merge_20240316_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='servernode',
            name='messageAPI',
            field=models.URLField(default='Remote', unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='remoteFollowAPI',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/api/user/<name>/following/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='user',
            name='remoteInboxAPI',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/api/msgs/create/'),
        ),
        migrations.AddField(
            model_name='user',
            name='remoteOpenapi',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/openapi/'),
        ),
        migrations.AddField(
            model_name='user',
            name='server_node_name',
            field=models.CharField(blank=True, default='Local', max_length=30),
        ),
        migrations.AlterField(
            model_name='servernode',
            name='host',
            field=models.URLField(default='Remote', unique=True),
        ),
        migrations.AlterField(
            model_name='servernode',
            name='name',
            field=models.CharField(default='Remote', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='servernode',
            name='userAPI',
            field=models.URLField(default='Remote', unique=True),
        ),
    ]
